# Generated by Django 2.1.4 on 2018-12-27 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('language', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Open', 'open'), ('Closed', 'closed')], max_length=4)),
                ('urgency', models.CharField(choices=[('Hot', 'hot'), ('Usual', 'usual')], max_length=5)),
            ],
        ),
    ]
